var quotes = [
    "Strong minds discuss ideas, average minds discuss events, weak minds discuss people.",
    "There is no passion to be found in playing small - in settling for a life that is any less than the one you are capable of living.",
    "The journey of a thousand miles begins with one step. ",
    "The brave man is he who overcomes not only his enemies but his pleasures",
    "Throw moderation to the winds, and the greatest pleasures bring the greatest pains.",
    "The wrongdoer is more unfortunate than the man wronged. ",
    "Is man merely a mistake of God's? Or God merely a mistake of man's?",
    "Life contains but two tragedies. One is not to get your heart’s desire; the other is to get it",
    "The secret of happiness, you see is not found in seeking more, but in developing the capacity to enjoy less.",
    "I cannot teach anybody anything. I can only make them think.",
    "Entities should not be multiplied unnecessarily",
    "The unexamined life is not worth living",
    "There is only one good, knowledge, and one evil, ignorance",
    "If God did not exist, it would be necessary to invent Him",
    "He who is unable to live in society, or who has no need because he is sufficient for himself, must be either a beast or a god",
    "That which does not kill us makes us stronger.",
    "Whoever fights monsters should see to it that in the process he does not become a monster. And if you gaze long enough into an abyss, the abyss will gaze back into you.",
    "A promise to love someone forever, then, means, 'As long as I love you I will render unto you the actions of love; if I no longer love you, you will continue to receive the same actions from me, if for other motives",
    "God is dead. God remains dead. And we have killed him. Yet his shadow still looms. How shall we comfort ourselves, the murderers of all murderers? What was holiest and mightiest of all that the world has yet owned has bled to death under our knives; who will wipe this blood off us? What water is there for us to clean ourselves?",
    "The true man wants two things: danger and play. For that reason he wants woman, as the most dangerous plaything.",
    "Perpetual optimism is a force multiplier.",
    "It is better to be feared than loved, if you cannot be both.",
    "I wonder how Maddie is doing",
    "Hope in reality is the worst of all evils because it prolongs the torments of man.",
    "They misunderestimated me",
    "My advice to you is get married: If you find a good wife you’ll be happy; if not, you’ll become a philosopher.",
    "To live is to suffer, to survive is to find some meaning in the suffering"
]
module.exports = quotes